# Generated by Django 5.2.8 on 2026-01-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='diabetes_type',
            field=models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2')], default='type1', max_length=10),
        ),
    ]
