# Generated by Django 5.2.8 on 2026-01-30 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userpreferences_diabetes_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='diabetes_type',
        ),
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabetes_type', models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2')], default='type1', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
