services:
  db:
    image: postgres:17
    container_name: glucolog_db_dev
    env_file: .env.dev

    ports:
      - "5433:5432"

    environment:

      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - glucolog_postgres_dev:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  glucolog_postgres_dev:
