# Generated by Django 5.2.8 on 2026-03-09 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_userpreferences_delete_insulinlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreferences',
        ),
    ]
