"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(BASE_DIR / ".env")

sendgrid_env = environ.Env()
environ.Env.read_env(BASE_DIR / "sendgrid.env")

# check debugging status from .env
DEBUG = env("DEBUG")
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# In dev (DEBUG=True) fall back to localhost so no config is needed; in
# production the real hostnames MUST be supplied via the ALLOWED_HOSTS env var.
ALLOWED_HOSTS = env.list(
    "ALLOWED_HOSTS", default=["localhost", "127.0.0.1"] if DEBUG else []
)

# --- Production security hardening ---
# When DEBUG is False these lock the app down for HTTPS. They assume a
# TLS-terminating reverse proxy (nginx/Caddy) sits in front of gunicorn, per the
# Oracle deployment plan. Each toggle defaults to "on in prod, off in dev" but is
# individually overridable via env, so the same settings file serves both.

# Domains allowed to POST to us (Origin check on secure requests). Needed when
# the site is reached via a custom domain/subdomain; e.g.
# CSRF_TRUSTED_ORIGINS=https://glucolog.example.com
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

# Trust the proxy's X-Forwarded-Proto header so Django knows the original request
# was HTTPS. Only safe when a proxy you control terminates TLS and sets it —
# without this, SECURE_SSL_REDIRECT below would cause an infinite redirect loop.
if env.bool("USE_X_FORWARDED_PROTO", default=not DEBUG):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=not DEBUG)
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = True

# HSTS: start at one week in prod so a misconfiguration is recoverable; raise to a
# year (31536000) and consider preload once HTTPS is proven stable.
SECURE_HSTS_SECONDS = env.int(
    "SECURE_HSTS_SECONDS", default=0 if DEBUG else 60 * 60 * 24 * 7
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS", default=not DEBUG
)
SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=not DEBUG)


# Application definition

INSTALLED_APPS = [
    "users",
    "landing",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # new
    "anymail",
    "logs",
    "dashboard",
    "main",
    "crispy_forms",
    "crispy_bootstrap5",
]

# email service
EMAIL_BACKEND = "anymail.backends.sendgrid.EmailBackend"

ANYMAIL = {
    "SENDGRID_API_KEY": sendgrid_env("SENDGRID_API_KEY"),
}

DEFAULT_FROM_EMAIL = sendgrid_env("DEFAULT_FROM_EMAIL", default="vchichovv@gmail.com")
SERVER_EMAIL = sendgrid_env("SERVER_EMAIL", default="vchichovv@gmail.com")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # new
    "main.middleware.NoCacheMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=env("DATABASE_URL"),
        conn_max_age=0,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Skopje"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

STORAGES = {
    "staticfiles": {"BACKEND": STATICFILES_STORAGE},
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
}

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


AUTH_USER_MODEL = "users.User"  # new

CRISPY_TEMPLATE_PACK = "bootstrap5"


LOGIN_URL = "glucolog-login"
