# Generated by Django 5.2.7 on 2025-11-12 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucoselog',
            name='measured_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='insulinlog',
            name='taken_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='eaten_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
