# Generated by Django 5.2.7 on 2025-11-12 19:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_glucoselog_measured_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucoselog',
            name='measured_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='eaten_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
