# Generated by Django 5.2.8 on 2025-11-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_glucoselog_measured_at_alter_meallog_eaten_at')
    ]

    operations = [
        migrations.AlterField(
            model_name='meallog',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
