# Generated by Django 5.2.8 on 2025-11-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_alter_meallog_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='insulinlog',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insulinlog',
            name='insulin_type',
            field=models.CharField(choices=[('basal', 'Basal'), ('bolus', 'Bolus')], max_length=10),
        ),
        migrations.AlterField(
            model_name='insulinlog',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
