# Generated by Django 5.2.8 on 2025-11-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_insulinlog_brand_alter_insulinlog_insulin_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glucoselog',
            name='context',
            field=models.CharField(choices=[('fasting', 'Fasting'), ('before meal', 'Before meal'), ('after meal', 'After meal'), ('bedtime', 'Bedtime'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='glucoselog',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='glucoselog',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
