# Generated by Django 5.2.8 on 2026-01-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_remove_meallog_desc_meallog_calories_meallog_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insulinlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insulinlog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
