# Generated by Django 5.2.8 on 2026-01-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0011_insulinlog_deleted_at_insulinlog_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='glucoselog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glucoselog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
