# Generated by Django 5.2.8 on 2026-01-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0012_glucoselog_deleted_at_glucoselog_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
