# Generated by Django 5.2.8 on 2026-08-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0013_meallog_deleted_at_meallog_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucoselog',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
